config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}

  resources :users
  resources :order_items
  resources :orders
  resources :images
  resources :plans
  resources :packages
  resources :services
  resources :divisions
  resources :cities do
    get :homePage, :on => :collection
    get :destinations, :on => :collection
    get :location_based_packages, :on => :collection
    get :aboutUs, :on => :collection
    get :contactUs, :on => :collection
    get :add_services_to_session, :on => :collection
    get :service_based_city_pakages, :on => :collection
    get :service_based_city_pakages1, :on => :collection
    get :service_based_packages, :on => :collection
    get :service_based_packages1, :on => :collection
    get :billing_detail, :on => :collection
    get :change_cart_items, :on => :collection
    post :place_order, :on => :collection
    get :pay_zippy_response, :on => :collection
  end


  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"


  resources :sessions, only: [:new, :create, :destroy]
  match 'login', :to => 'sessions#new', :via => [:get, :post]
  match 'logout', :to => 'sessions#destroy', :via => [:get, :post]



  root 'cities#homePage'
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to '/services', notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to '/services', notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :is_active,:image)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Service Name', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label :description, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_area :description, :class => 'form-control', :placeholder => 'description', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :is_active, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_active %>
      </div>

      <div class="actions">
        <%= form.submit(:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Service') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', services_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', service: @service %>
  </div>
</div>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Services') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Service', new_service_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Name</th>
      <th>Description</th>
      <th> Images</th>
      <th>Is active</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= image_tag(service.image.present? ? service.image : '', :width => '100px')%></td>
        <td><%= service.is_active %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/services/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Service') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', services_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', service: @service %>
  </div>
</div>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Division:</strong>
  <%= @service.division_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @service.city_id %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @service.is_active %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>