config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}

  resources :users
  resources :order_items
  resources :orders
  resources :images
  resources :plans
  resources :packages
  resources :services
  resources :divisions
  resources :cities do
    get :homePage, :on => :collection
    get :destinations, :on => :collection
    get :location_based_packages, :on => :collection
    get :aboutUs, :on => :collection
    get :contactUs, :on => :collection
    get :add_services_to_session, :on => :collection
    get :service_based_city_pakages, :on => :collection
    get :service_based_city_pakages1, :on => :collection
    get :service_based_packages, :on => :collection
    get :service_based_packages1, :on => :collection
    get :billing_detail, :on => :collection
    get :change_cart_items, :on => :collection
    post :place_order, :on => :collection
    get :pay_zippy_response, :on => :collection
  end


  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"


  resources :sessions, only: [:new, :create, :destroy]
  match 'login', :to => 'sessions#new', :via => [:get, :post]
  match 'logout', :to => 'sessions#destroy', :via => [:get, :post]



  root 'cities#homePage'
end

app/models/division.rb
class Division < ApplicationRecord
  has_one_attached :image
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to '/divisions', notice: 'Division was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to '/divisions', notice: 'Division was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:name, :content, :city_id,:image,:is_popular)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division, local: true) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label "Location Name ", :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Location Name', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label 'Description', :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_area :content, :class => 'form-control', :placeholder => 'Description', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label 'Division Name', :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:city_id, options_for_select(City.all.collect {|u| [u.name, u.id]}, @division.city_id), {:prompt => 'Select Division '}, :class => 'form-control') %>
      </div>
      <div class="form-group">
        <%= form.label :is_popular, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_popular %>
      </div>
      <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit( "Save Location",:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Location') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', divisions_url, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', division: @division %>
  </div>
</div>

app/views/divisions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Locations') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Location', new_division_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Name</th>
      <th>Content</th>
      <th>Division</th>
      <th>Popular</th>
      <th>Image</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.name %></td>
        <td><%= division.content %></td>
        <td><%= City.find_by_id(division.city_id).try(:name) %></td>
        <td><%= division.is_popular %></td>
        <td><%= image_tag(division.image.present? ? division.image : '', :width => '100px')%></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/divisions/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Location') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', divisions_url, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', division: @division %>
  </div>
</div>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @division.content %>
</p>

<p>
  <strong>City:</strong>
  <%= @division.city_id %>
</p>

<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>