config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}

  resources :users
  resources :order_items
  resources :orders
  resources :images
  resources :plans
  resources :packages
  resources :services
  resources :divisions
  resources :cities do
    get :homePage, :on => :collection
    get :destinations, :on => :collection
    get :location_based_packages, :on => :collection
    get :aboutUs, :on => :collection
    get :contactUs, :on => :collection
    get :add_services_to_session, :on => :collection
    get :service_based_city_pakages, :on => :collection
    get :service_based_city_pakages1, :on => :collection
    get :service_based_packages, :on => :collection
    get :service_based_packages1, :on => :collection
    get :billing_detail, :on => :collection
    get :change_cart_items, :on => :collection
    post :place_order, :on => :collection
    get :pay_zippy_response, :on => :collection
  end


  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"


  resources :sessions, only: [:new, :create, :destroy]
  match 'login', :to => 'sessions#new', :via => [:get, :post]
  match 'logout', :to => 'sessions#destroy', :via => [:get, :post]



  root 'cities#homePage'
end

app/models/city.rb
class City < ApplicationRecord
  has_one_attached :image
  #has_many_attached :images
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  include ApplicationHelper
  include CitiesHelper
  include CcAvenueHelper
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  skip_authorize_resource :only => [:index,:homePage, :location_based_packages, :destinations, :aboutUs, :contactUs, :service_based_city_pakages, :add_services_to_session, :service_based_packages, :service_based_city_pakages, :service_based_packages1, :billing_detail, :change_cart_items, :place_order, :service_based_city_pakages1]
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    respond_to do |format|
      if @city.save

        format.html {redirect_to "/cities", notice: 'City was successfully created.'}
        format.json {render :show, status: :created, location: @city}
      else
        format.html {render :new}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html {redirect_to "/cities", notice: 'City was successfully updated.'}
        format.json {render :show, status: :ok, location: @city}
      else
        format.html {render :edit}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html {redirect_to cities_url, notice: 'City was successfully destroyed.'}
      format.json {head :no_content}
    end
  end


  def homePage
    session[SessionConstants::SELECTED_MENU_ITEM] = 'homePage'
    @services = Service.all
    @cities = City.where("is_popular=?", true)
    @locations = Division.where("is_popular=?", true)
    render :layout => 'application1'
  end

  def location_based_packages
    @division = Division.find_by_id(params[:location_id]) if params[:location_id].present?
    @packages = Package.where('division_id=?', @division.id) if @division.present?
    render :layout => 'application1'
  end

  def destinations
    session[SessionConstants::SELECTED_MENU_ITEM] = 'destinations'
    @services = Service.all
    @cities = City.all
    render :layout => 'application1'
  end

  def aboutUs
    session[SessionConstants::SELECTED_MENU_ITEM] = 'aboutUs'
    render :layout => 'application1'
  end

  def contactUs
    session[SessionConstants::SELECTED_MENU_ITEM] = 'contactUs'
    render :layout => 'application1'
  end

  def add_services_to_session
    @services = Service.all
    session[SessionConstants::SESSION_SERVICES] = ''
    session[SessionConstants::SESSION_SERVICES] = params[:service]
    if session[SessionConstants::SESSION_SERVICES].present? && !session[SessionConstants::SESSION_SERVICES].to_i.eql?(0)
      @cities = []
      @service_base_cities = []
      @packages = Package.where("service_id=?", session[SessionConstants::SESSION_SERVICES])
      @packages.each do |package|
        @service_base_cities << package.city_id if !@service_base_cities.include?(package.city_id)
      end
      @service_base_cities.each do |sbc|
        @city = City.find_by_id(sbc)
        @cities << @city
      end
    else
      @cities = City.all
    end
  end

  def service_based_city_pakages
    @location_based_packages = []
    if params[:city_id].present?
      @city = City.find_by_id(params[:city_id])
      @divisions = Division.where("city_id =?", @city.id) if @city.present?
      @service = Service.find_by_id(params[:service_id]) if params[:service_id].present?
      @divisions.each do |division|
        if @service.present?
          @packages = Package.where("city_id =? and service_id =? and division_id =?", @city.id, @service.id, division.id)
        else
          @packages = Package.where("city_id =? and division_id=?", @city.id, division.id)
        end
        @location_based_packages << LocationBasedPackages.new(division.name, @packages) if @packages.present?
      end
    end
    render :layout => 'application1'
  end


  def service_based_city_pakages1

    if params[:city_id].present?
      @city = City.find_by_id(params[:city_id])
      @service = Service.find_by_id(params[:service_id]) if params[:service_id].present?
      if @service.present?
        @packages = Package.where("city_id =? and service_id =?", @city.id, @service.id).order("division_id desc")
      else
        @packages = Package.where("city_id =?", @city.id).order("division_id desc")
      end
    end
    render :layout => 'application1'
  end


  def service_based_packages

    @service_base_cities = []
    @cities = []

    @service = Service.find_by_id(params[:service_id]) if params[:service_id].present?
    @allpackages = Package.where("service_id=?", @service.id) if @service.present?
    if @allpackages.present?
      @allpackages.each do |package|
        @service_base_cities << package.city_id if !@service_base_cities.include?(package.city_id)
      end
      @service_base_cities.each do |sbc|
        @city = City.find_by_id(sbc)
        @cities << @city
      end
    end

    render :layout => 'application1'
  end

  def service_based_packages1

    @service_base_cities = []
    @cities = []

    @service = Service.find_by_id(params[:service_id]) if params[:service_id].present?
    @allpackages = Package.where("service_id=?", @service.id) if @service.present?
    if @allpackages.present?
      @allpackages.each do |package|
        @service_base_cities << package.city_id if !@service_base_cities.include?(package.city_id)
      end
      @service_base_cities.each do |sbc|
        @city = City.find_by_id(sbc)
        @cities << @city
      end
    end

    render :layout => 'application1'
  end

  def billing_detail
    @package = Package.find_by_id(params[:package_id])
    @order = Order.new
    render :layout => 'application2'
  end

  def change_cart_items
    session[SessionConstants::SESSION_ID] = UUIDTools::UUID.random_create.to_s.delete '-' if session[SessionConstants::SESSION_ID].blank?
    @plan = Plan.find_by_package_id_and_pakage_type(params[:package_id], params[:package_type])
    if @plan.present?
      @cartItem = CartItem.find_by_plan_id_and_session_id(@plan.id, session[SessionConstants::SESSION_ID])
      if @cartItem.blank? && !params[:no_of_items].equal?(0)
        @cartItem = CartItem.new
        @cartItem.package_id = @plan.package_id
        @cartItem.plan_id = @plan.id
        @cartItem.no_of_items = params[:no_of_items]
        @cartItem.session_id = session[SessionConstants::SESSION_ID]
        @cartItem.price = (@plan.price.to_d * params[:no_of_items].to_i).to_d
        @cartItem.save
      else
        if params[:no_of_items].to_i == 0
          @cartItem.destroy
        else
          @cartItem.no_of_items = params[:no_of_items]
          @cartItem.price = (@plan.price.to_d * params[:no_of_items].to_i).to_d
          @cartItem.save
        end
      end
    end
  end

  def place_order
    @order = Order.new
    @order.first_name = params[:order][:first_name]
    @order.last_name = params[:order][:last_name]
    @order.buyer_phone_no = params[:order][:buyer_phone_no]
    @order.buyer_email_address = params[:order][:buyer_email_address]
    @order.status = 'Created'
    random_id = UUIDTools::UUID.random_create.to_s.delete '-'
    random_id[0..2] = ''
    @order.merchant_transaction_id = random_id
    @order.save!
    @cartItems = CartItem.where('session_id =?', session[SessionConstants::SESSION_ID])
    totalPrice = 0.0
    @cartItems.each do |item|
      @order_item = OrderItem.new
      @order_item.order_id = @order.id
      @order_item.package_id = item.package_id
      @order_item.plan_id = item.plan_id
      @order_item.total_amount = item.price
      @order_item.no_of_items = item.no_of_items
      totalPrice += item.price
      @order_item.save
    end
    @order.transaction_amount = totalPrice
    @order.save
    if @order.present? && @order_item.present? && params[:commit].present?
      @all_order_items = OrderItem.where("order_id=?", @order.id)
      sms = "Dear #{@order.first_name}Your order was booked at APTDC with OrderID #{@order.id},TrnID #{@order.merchant_transaction_id},Fare #{@order.transaction_amount}."
      send_sms(@order.buyer_phone_no, sms, 'order booked', @order.id)
      UserMailer.orderbooked(@order, @all_order_items).deliver
      reset_session
      payment_url = cc_avenue_details(@order, 'http://java.meritcampus.com/pay_zippy_response')
      redirect_to payment_url
    else
      redirect_to "/cities/billing_detail?package_id=#{params[:package_id]}"
    end
  end


  def pay_zippy_response

  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:name, :description, :estimated_visit_days, :image, :is_popular)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
  class LocationBasedPackages
    attr_accessor :division_name, :packages
    def initialize(division_name, packages)
      @division_name = division_name
      @packages = packages
    end
  end

end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>
      <ul>
        <% city.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Division Name', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :description, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_area :description, :class => 'form-control', :placeholder => 'Description', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :estimated_visit_days, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.number_field :estimated_visit_days, :class => 'form-control', :placeholder => 'estimated_visit_days', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :is_popular, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_popular %>
      </div>

      <!--    <div class="form-group">-->
      <%#= form.label :images %>
      <%#= form.file_field :images, multiple: true ,:class =>"form-control" %>
      <!--    </div>-->

      <div class="actions">
        <%= form.submit('New Division',:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/cities/_selected_cart_items.html.erb
<style>

  #mytable1 td {
    border: none !important;
    background-color: white;
    text-align: left;
    color: black;
    padding: 10px;
    font-weight: 600;
    font-family: Roboto;
  }

  #mytable1 th {
    border: none !important;
    text-align: left;
    color: black;
    padding: 10px;
    font-family: "Arial Black";
  }

  #mytable td {
    border: none !important;
    text-align: left;
    background-color: white;
    padding: 15px 5px;
    color: black;
    text-transform: capitalize;
    font-family: Roboto;
  }

  #mytable th {
    border: none !important;
    text-align: left;
    padding: 15px 5px;
    text-transform: capitalize;
    font-family: Roboto;

  }
</style>

<div class="page_content"> Your Order</div>
<div style="padding: 5px;border-bottom: 1px solid #e6e6e6"></div>
<br/>
<div>
  <% @cartItems = CartItem.where('session_id = ?', session[ApplicationHelper::SessionConstants::SESSION_ID]) %>
  <% if @cartItems.present? %>

    <table class="table table-hover" id="mytable" style=" background-color: ghostwhite;padding: 5px">

      <tr>
        <th style="border: none !important;"> </th>
        <th>Package Details</th>
        <th> Qty.</th>
        <th> price</th>
      </tr>
      <% @subTotal = 0 %>
      <% @cartItems.each do |item| %>
        <tr style="border-bottom: 1px solid #e6e6e6">
          <td><%= image_tag(Package.find_by_id(item.package_id).try(:image), :height => '100px', :width => '100px') %> </td>
          <td>
            <div style="font-family: 'Arial Black' !important;padding: 5px 0px;color: #06699B"><%= City.find_by_id(Package.find_by_id(item.package_id).try(:city_id)).try(:name) %></div>
            <div style="font-family: 'Arial Black' !important;padding-bottom: 5px "><%= Package.find_by_id(item.package_id).try(:name) %></div>
            <div style="color: #0c0c0c;font-weight: 600;"><%= Plan.find_by_id(item.plan_id).try(:pakage_type) %>
              - Rs <%= Plan.find_by_id(item.plan_id).try(:price) %> <sub>/ per person</sub></div>
            <div>
              <a onclick="myFunction(0,'<%= Plan.find_by_id(item.plan_id).try(:pakage_type) %>','<%= item.package_id %>')" class="btn-xs btn-danger" style="color: white;background-color: red !important;cursor: pointer">Remove</a>
            </div>
          </td>
          <td style="font-weight: 600"><%= item.no_of_items %></td>
          <td style="font-weight: 600"> Rs. <%= item.price %></td>
          <% @subTotal = @subTotal += item.price %>
        </tr>
      <% end %>
    </table>

    <div class="row" style="margin: 0px">
      <div class="col-sm-6"></div>
      <div class="col-sm-6" style="border: 1px solid black;border-radius: 5px !important;">
        <table class="table table-hover" id="mytable1" style=" background-color: ghostwhite;padding: 10px;">
          <tr>
            <td>Sub Total</td>
            <td> Rs. <%= @subTotal %></td>
          </tr>
          <tr>
            <td>Tax</td>
            <td> Rs. 0.0</td>
          </tr>
          <tr>
            <th>Total Price</th>
            <th style="color: #ff7550"> Rs. <%= @subTotal %></th>
          </tr>
        </table>
      </div>
    </div>

  <% end %>
</div>

app/views/cities/_service_based_cities.html.erb
<div class="top1">
  <div class="top-left1 search-box">
    <input type="text" id="searchy" placeholder="Search Elements" style="height:30px;"/>
  </div>
  <div class="top-right1">
    <% @services.each_with_index do |service, index| %>
      <a class='tag1 <%= session[ApplicationHelper::SessionConstants::SESSION_SERVICES].present? && session[ApplicationHelper::SessionConstants::SESSION_SERVICES].to_i.eql?(service.id) ? "tag-active1" : "" %>' style="text-transform: uppercase" onclick="select_services('<%= service.id %>')"><%= service.name %></a>
    <% end %>
    <a class='tag1 <%= session[ApplicationHelper::SessionConstants::SESSION_SERVICES].present? && session[ApplicationHelper::SessionConstants::SESSION_SERVICES].to_i.eql?(0) ? "tag-active1" : "" %>' style="text-transform: uppercase" onclick="select_services(0)">All</a>
  </div>
</div>
<div class="list-body1">
  <% @cities.each_with_index do |city, index| %>
    <div class="col-md-3 explore">
      <div class="list-el1 taga-2 taga-3">
        <div class="owl-item active" style="width: 100%; margin-right: 30px;">
          <div class="item tg-populartour">
            <figure>
              <a href="/cities/service_based_city_pakages1?city_id=<%= city.id %>&&service_id=<%= session[ApplicationHelper::SessionConstants::SESSION_SERVICES].present? ? session[ApplicationHelper::SessionConstants::SESSION_SERVICES] : 0 %>">
                <%= image_tag(city.image, :width => '100%') %>
              </a>
            </figure>
            <div class="tg-populartourcontent">
              <div class="tg-populartourtitle">
                <h3 class="movieTitle" style="font-family: Roboto">
                  <a href="/cities/service_based_city_pakages1?city_id=<%= city.id %>&&service_id=<%= session[ApplicationHelper::SessionConstants::SESSION_SERVICES].present? ? session[ApplicationHelper::SessionConstants::SESSION_SERVICES] : 0 %>"><%= city.name %></a>
                </h3>
              </div>
              <div class="tg-description">
                <p class="OverFlow"><%= city.description %></p>
              </div>
              <div class="tg-populartourfoot">
                <div class="tg-durationrating">
                  <span class="tg-tourduration"><%= city.estimated_visit_days %> Days</span>
                </div>
                <div class="tg-pricearea">
                  <a href="/cities/service_based_city_pakages1?city_id=<%= city.id %>&&service_id=<%= session[ApplicationHelper::SessionConstants::SESSION_SERVICES].present? ? session[ApplicationHelper::SessionConstants::SESSION_SERVICES] : 0 %>" style="cursor: pointer;color: #ff7550;font-weight: 600;font-family: Roboto">Explore</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
    function select_services(value) {
        if (value != null || value != '') {
            $.ajax('/cities/add_services_to_session?service=' + value)
        }
    }
</script>

app/views/cities/aboutUs.html.erb
<style>
  .page_content {
    font-size: 22px;
    font-weight: 400;
    font-family: 'Roboto';
    color: black;
    padding: 5px;
  }

  .package_name {
    font-family: Montserrat;
    font-size: 24px;
    font-weight: 600;
    color: #000000;
    padding: 5px !important;
  }
</style>

<section class="tg-parallax tg-innerbanner" data-appear-top-offset="600" data-parallax="scroll" data-image-src="/images/about_banner.jpg">
  <div class="tg-sectionspace tg-haslayout">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h1>About us</h1>

        </div>
      </div>
    </div>
  </div>
</section>
<main id="tg-main" class="tg-main tg-haslayout">
  <br/><br/>
</main>

app/views/cities/add_services_to_session.js.erb
$('#homePage_city_content').html("<%= escape_javascript(render(:partial => "service_based_cities")) %>");

app/views/cities/billing_detail.html.erb
<style>
  .page_content {
    font-size: 22px;
    font-weight: 400;
    font-family: 'Roboto';
    color: black;
    padding: 5px;
  }

  .package_name {
    font-family: Montserrat;
    font-size: 24px;
    font-weight: 600;
    color: #000000;
    padding: 5px !important;
  }
</style>

<section class="tg-parallax tg-innerbanner" data-appear-top-offset="600" data-parallax="scroll" data-image-src="<%= url_for(@package.image) %>">
  <div class="tg-sectionspace tg-haslayout">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h1><%= @package.name %></h1>

        </div>
      </div>
    </div>
  </div>
</section>
<main id="tg-main" class="tg-main tg-haslayout">
  <div class="tg-sectionspace tg-haslayout">
    <div class="container">
      <%= form_for(@order, :url => '/cities/place_order') do |f| %>
        <div class="row" style="margin: 0px">
          <div class="col-sm-6" style="padding: 5px;border-right: 2px solid #e6e6e6">
            <div style="padding-right:30px !important;">
              <div class="page_content"> Billing Details</div>
              <div style="padding: 5px;border-bottom: 1px solid #e6e6e6"></div>
              <br/>
              <div class="package_name"><%= @package.name %></div>
              <br/>
              <div class="clearfix"></div>
              <div class="row">
                <% plans = Plan.where("package_id =?", @package.id) %>
                <% plans.each do |plan| %>
                  <div class=" col-sm-6">
                    <div class="tg-pricearea" style="float:left;">
                      <span style="float:left;"><%= plan.pakage_type %></span><br>
                      <h4 style="float:left; font-size:14px;"> <%= plan.price %><sub>/ per person</sub></h4>
                    </div>
                    </br></br>
                  </div>
                <% end %>
              </div>
              <hr>

              <div class="row">

                <div class="col-sm-6">

                  <% if @order.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this payment from being
                        processed:</h2>

                      <ul>
                        <% @order.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <%= hidden_field_tag 'package_id', @package.id %>

                  <div class="form-group">
                    <div class="tg-formicon"><i class="icon-user-check"></i></div>
                    <br/>
                    <%= select_tag 'adults_no', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), :prompt => "Adults", :onchange => "myFunction(this.value,'Adults',#{@package.id})", :class => "form-control" %>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <div class="tg-formicon"><i class="icon-user"></i></div>
                    <br/>
                    <%= select_tag 'child_no', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), :prompt => "Child", :onchange => "myFunction(this.value,'Child',#{@package.id})", :class => "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <%= label_tag('', 'First Name', :class => 'control-label field_label_style') %>

                    <%= f.text_field :first_name, :placeholder => 'First Name', :class => "form-control", :required => true %>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <%= label_tag('', 'Last Name', :class => 'control-label field_label_style') %>
                    <%= f.text_field :last_name, :placeholder => 'Last Name', :class => "form-control", :required => true %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= label_tag('', 'Email', :class => 'control-label field_label_style') %>
                <%= f.text_field :buyer_email_address, :class => "form-control", :required => true, :pattern => ".+@gmail.com" %>
              </div>
              <div class="form-group">
                <%= label_tag('', 'Phone Number', :class => 'control-label field_label_style') %>
                <%= f.text_field :buyer_phone_no, :placeholder => 'PhoneNumber', :pattern => "[0-9].{0}|.{10}", :title => 'Mobile number should be 10 digits', :onkeypress => 'return event.charCode >= 48 && event.charCode <= 57', :maxlength => "10", :class => "form-control", :required => true %>
              </div>
            </div>
          </div>
          <div class="col-sm-6" style="padding: 5px;">
            <div style="padding-left:30px !important;">
              <br/>
              <div id="cart_content"><%= render :partial => 'selected_cart_items' %></div>
            </div>
          </div>
        </div>
        <br/>
        <div class="text-right"><%= f.submit "CHECKOUT", :class => 'btn btn-primary' %></div>
      <% end %>
    </div>
  </div>
</main>


<script>
    function myFunction(no_of_items, package_type, package_id) {
        var no_of_items = no_of_items == "" ? 0 : no_of_items;
        var package_type = package_type;
        var package_id = package_id;
        if ((no_of_items != null || no_of_items != '') && package_type != null && package_id != null) {
            $.ajax('/cities/change_cart_items?no_of_items=' + no_of_items + '&&package_type=' + package_type + '&&package_id=' + package_id)
        }
    }
</script>

app/views/cities/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Division') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', cities_url, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', city: @city %>
  </div>
</div>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Divisions') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Division', new_city_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Name</th>
      <th>Description</th>
      <th>Estimate Visit Days</th>
      <th>popular</th>
      <th>Image</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.description %></td>
        <th><%= city.estimated_visit_days %></th>
        <td><%= city.is_popular %></td>
        <td><%= image_tag(city.image.present? ? city.image : '', :width => '100px')%></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/cities/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Division') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', cities_url, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', city: @city %>
  </div>
</div>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @city.description %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>